### ISSUE TITLE
Optuna-distributed in HPC environment

### ISSUE THREAD

**Issue by ikunabel** [xadrianzetx/optuna-distributed#74]
Dear Adrian Zuber,

I would like to ask whether optuna-distributed could be used with a MySQL storage on an HPC cluster. I am currently trying to parallelize my optimization by submitting multiple processes to Slurm, which usually comes along with a concurrency overhead. Having discovered other approaches recently (thread-based vs process-based, InMemory storage vs RDB storage, dask-optuna vs optuna-distributed, etc.), I wonder what parallelization config you consider as the best. I would highly appreciate if you could perhaps share your experience on this.

Best regards
Ábel

**Comment by xadrianzetx** [comment]
It depends on how much control you have over the cluster. If you can install Dask there, then I think it would be worth giving Optuna-distributed or Optuna's builtin Dask integration a go, since you are free to experiment with storage options (Optuna-distributed supports both in-memory and RDB). If you have to use Slurm as scheduler, then I'd follow [Optuna's parallelization recipe](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html#easy-parallelization). RDB will be required in that case.
